# NumPy (Numerical Python) is a Python library that:

* Efficiently stores and processes large, multi-dimensional arrays
* Provides fast mathematical operations
* Serves as the base foundation for scientific computing and data analysis

## Array Creation

## 1 D array

In [2]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


## 2 D array

In [5]:
import numpy as np
a2=np.array([[1,2,3,4],[5,6,7,8]])
print(a2)

[[1 2 3 4]
 [5 6 7 8]]


## 3 D array

In [2]:
import numpy as np
a3=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print(a3)


[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


 # Useful Attributes

 # NumPy Array Attributes Reference

| Attribute | Function/Syntax | Description | Example Output |
|-----------|----------------|-------------|----------------|
| **Shape** | `a.shape` | Returns the dimensions of the array (rows, columns, etc.) | `(2, 3)` |
| **Dimensions** | `a.ndim` | Returns the number of dimensions (1D, 2D, 3D...) | `2` |
| **Data Type** | `a.dtype` | Returns the data type of array elements (int, float, etc.) | `int64`, `float32` |
| **Size** | `a.size` | Returns the total number of elements in the array | `6` |



In [ ]:
import numpy as np

# Create a sample 2D array
a = np.array([[1, 2, 3], [4, 5, 6]])

print(f"Shape: {a.shape}")      # Output: (2, 3)
print(f"Dimensions: {a.ndim}")  # Output: 2
print(f"Data Type: {a.dtype}")  # Output: int64 
print(f"Size: {a.size}")        # Output: 6

(2, 2, 4)


# Array Creation Functions
# NumPy Array Creation Functions Reference

| Function | Syntax | Example | Description | Output |
|----------|--------|---------|-------------|--------|
| **Zeros** | `np.zeros()` | `np.zeros((2, 3))` | Creates an array filled with zeros | 2 rows × 3 columns |
| **Ones** | `np.ones()` | `np.ones((3, 2))` | Creates an array filled with ones | 3 rows × 2 columns |
| **Full** | `np.full()` | `np.full((2, 2), 7)` | Creates an array filled with a specific value | 2 rows × 2 columns |
| **Identity** | `np.eye()` | `np.eye(3)` | Creates an identity matrix (1s on diagonal, 0s elsewhere) | 3 × 3 square matrix |
| **Range** | `np.arange()` | `np.arange(0, 10, 2)` | Creates a range of numbers with specified step | [0 2 4 6 8] |
| **Linear Space** | `np.linspace()` | `np.linspace(0, 1, 5)` | Creates evenly spaced values between start & end | 5 values |
| **Random Float** | `np.random.rand()` | `np.random.rand(2, 3)` | Creates random float numbers (0 to 1) | 2 rows × 3 columns |
| **Random Integer** | `np.random.randint()` | `np.random.randint(1, 10, (2, 4))` | Creates random integers within specified range | 2 rows × 4 columns |



## Some Basic method  related to array creation

In [4]:
a4=np.ones((3,4))
print(a4)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [5]:
a4=np.zeros((2,5))
print(a4)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [6]:
a4=np.full((4,4),9)
print(a4)

[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


In [7]:
a4=np.eye(5)
print(a4)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [9]:
a4=np.arange(5,25,5)
print(a4)

[ 5 10 15 20]


In [10]:
a4=np.linspace(0,1,10)
print(a4)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [12]:
a5=np.random.rand(3,3)
print(a5)

[[0.14957587 0.13624275 0.5657611 ]
 [0.03106808 0.60666727 0.73008088]
 [0.54938241 0.06306858 0.82013585]]


In [13]:
a6=np.random.randint(10,100,(3,2))
print(a6)

[[70 36]
 [51 23]
 [51 13]]


# Array Operations

 ### Element-wise Arithmetic Operations

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition:", a + b)        
print("Subtraction:", a - b)   
print("Multiplication:", a * b)
print("Division:", a / b)        
print("Power:", a ** 2)         


Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]
Power: [1 4 9]


### Aggregate Functions (Summary Statistics)

In [16]:
arr = np.array([10, 20, 30, 40])

print("Sum:", arr.sum())          
print("Mean:", arr.mean())        
print("Max:", arr.max())          
print("Min:", arr.min())           
print("Standard Deviation:", arr.std())  


Sum: 100
Mean: 25.0
Max: 40
Min: 10
Standard Deviation: 11.180339887498949


### Array Comparison

In [18]:
a = np.array([1, 2, 3])
b = np.array([2, 2, 4])

print(a > b)   
print(a == b)
print(a!=b)  


[False False False]
[False  True False]
[ True False  True]



 Complete List of Matrix Operations in NumPy

| Operation Type            | Function / Syntax          | Description                              |
| ------------------------- | -------------------------- | ---------------------------------------- |
| **Addition**              | `a + b`                    | Element-wise addition                    |
| **Subtraction**           | `a - b`                    | Element-wise subtraction                 |
| **Element-wise Multiply** | `a * b`                    | Element-wise multiplication              |
| **Matrix Multiplication** | `np.dot(a, b)` or `a @ b`  | True matrix multiplication (dot product) |
| **Transpose**             | `a.T`                      | Swap rows and columns                    |
| **Inverse**               | `np.linalg.inv(a)`         | Matrix inverse (only for square matrix)  |
| **Determinant**           | `np.linalg.det(a)`         | Determinant of matrix                    |
| **Rank**                  | `np.linalg.matrix_rank(a)` | Rank of the matrix                       |
| **Trace**                 | `np.trace(a)`              | Sum of diagonal elements                 |
| **Eigenvalues/Vectors**   | `np.linalg.eig(a)`         | Eigenvalues and eigenvectors             |
| **Solve Linear Eq.**      | `np.linalg.solve(a, b)`    | Solve system of linear equations         |

**np.linalg is the linear algebra module inside NumPy — it gives advanced matrix functions.** 


In [19]:
import numpy as np

# Matrices
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print("Matrix A:\n", a)
print("Matrix B:\n", b)

# Element-wise addition
print("\nAddition (A + B):\n", a + b)

# Element-wise subtraction
print("\nSubtraction (A - B):\n", a - b)

# Element-wise multiplication
print("\nElement-wise Multiplication (A * B):\n", a * b)

# Matrix multiplication (dot product)
print("\nMatrix Multiplication (A @ B):\n", a @ b)  # same as np.dot(a, b)

# Transpose
print("\nTranspose of A:\n", a.T)

# Determinant
print("\nDeterminant of A:", np.linalg.det(a))

# Inverse
print("\nInverse of A:\n", np.linalg.inv(a))

# Trace (sum of diagonal)
print("\nTrace of A:", np.trace(a))

# Rank
print("\nRank of A:", np.linalg.matrix_rank(a))

# Eigenvalues and Eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(a)
print("\nEigenvalues of A:", eigenvalues)
print("Eigenvectors of A:\n", eigenvectors)

# Solving Linear System Ax = b
A = np.array([[2, 1], [1, 3]])
B = np.array([8, 13])
x = np.linalg.solve(A, B)
print("\nSolution of linear system Ax = b:\n", x)


Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]

Addition (A + B):
 [[ 6  8]
 [10 12]]

Subtraction (A - B):
 [[-4 -4]
 [-4 -4]]

Element-wise Multiplication (A * B):
 [[ 5 12]
 [21 32]]

Matrix Multiplication (A @ B):
 [[19 22]
 [43 50]]

Transpose of A:
 [[1 3]
 [2 4]]

Determinant of A: -2.0000000000000004

Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]

Trace of A: 5

Rank of A: 2

Eigenvalues of A: [-0.37228132  5.37228132]
Eigenvectors of A:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]

Solution of linear system Ax = b:
 [2.2 3.6]


# Indexing & Slicing

In [20]:
# Indexing in 1d Array
a = np.array([10, 20, 30, 40, 50])

print(a[0])   # First element → 10
print(a[-1])  # Last element → 50


10
50


In [21]:
# Indexing in 2D array
a = np.array([[1, 2, 3],
              [4, 5, 6]])

print(a[0, 0])  # First row, first column → 1
print(a[1, 2])  # Second row, third column → 6


1
6


In [22]:
# Sciling in 1D array
a = np.array([10, 20, 30, 40, 50])

print(a[1:4])    # From index 1 to 3 → [20, 30, 40]
print(a[:3])     # From start to index 2 → [10, 20, 30]
print(a[::2])    # Every second element → [10, 30, 50]


[20 30 40]
[10 20 30]
[10 30 50]


In [23]:
# Slicing in 2D Array
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(a[0:2, 1:])   # Rows 0–1, columns 1–2 → [[2,3],[5,6]]
print(a[:, 0])      # All rows, column 0 → [1, 4, 7]
print(a[1, :])      # Row 1, all columns → [4, 5, 6]


[[2 3]
 [5 6]]
[1 4 7]
[4 5 6]


### Deep Indexing & Slicing
You can access multiple specfic elements

In [ ]:
# Fancy Indexing (1D Array)
a=np.array([1,2,3,4,5,6,7,8,9])
print(a[[0,3,5,7]])

[1 4 6 8]


In [27]:
# Fancy Indexing (1D Array)
a=np.array([[1,2,3,4,5,6,7,8,9],[9,8,7,6,5,4,3,2,1],[3,4,3,7,8,9,4,32,7]])
print(a)

[[ 1  2  3  4  5  6  7  8  9]
 [ 9  8  7  6  5  4  3  2  1]
 [ 3  4  3  7  8  9  4 32  7]]


In [28]:
print(a[[0,2]])

[[ 1  2  3  4  5  6  7  8  9]
 [ 3  4  3  7  8  9  4 32  7]]


In [30]:
print(a[[0,2],[0,1]])

[1 4]


In [31]:
print(a[:,[1,2]])

[[2 3]
 [8 7]
 [4 3]]


In [33]:
print(a[[0,1]])

[[1 2 3 4 5 6 7 8 9]
 [9 8 7 6 5 4 3 2 1]]


In [34]:
print(a[:,[0,1]])

[[1 2]
 [9 8]
 [3 4]]


In [35]:
# Boolean Indexing (Filtering Elements)
a = np.array([5, 10, 15, 20, 25])
# Get all values > 10
print(a[a > 10])   # [15 20 25]

# Get even values
print(a[a % 2 == 0])  # [10 20]

[15 20 25]
[10 20]


In [36]:
# Modifying Using Boolean Mask
a[a>10]=0
print(a)

[ 5 10  0  0  0]


In [38]:
# Axis-Based Operations + np.where()
a = np.array([[1, 2, 3],
              [4, 5, 6]])

# Sum along rows (axis=1)
print("Row-wise sum:", a.sum(axis=1))  # → [ 6 15]

# Sum along columns (axis=0)
print("Column-wise sum:", a.sum(axis=0))  # → [5 7 9]

# Max along each row
print("Row-wise max:", np.max(a, axis=1))  # → [3 6]

# Mean of columns
print("Column-wise mean:", a.mean(axis=0))  # → [2.5 3.5 4.5]


Row-wise sum: [ 6 15]
Column-wise sum: [5 7 9]
Row-wise max: [3 6]
Column-wise mean: [2.5 3.5 4.5]


In [39]:
# np.where() — Conditional Selection
a = np.array([10, 15, 20, 25])

# Where values > 15, return "High", else "Low"
result = np.where(a > 15, "High", "Low")
print(result)  # → ['Low' 'Low' 'High' 'High']


['Low' 'Low' 'High' 'High']


In [40]:
# np.any() and np.all()
a = np.array([[1, 0],
              [3, 4]])

# Check if any value is 0 in rows
print(np.any(a == 0, axis=1))  # → [ True False]

# Check if all values are > 0 in columns
print(np.all(a > 0, axis=0))  # → [ True False]


[ True False]
[ True False]


###  Reshape, Flatten, and Stack

In [41]:
# Reshape convert 1D array to 2D Array
a = np.array([1, 2, 3, 4, 5, 6])
reshaped = a.reshape(2, 3)
print(reshaped)


[[1 2 3]
 [4 5 6]]


In [42]:
# Flatten 2D Array to 1D Array
a = np.array([[1, 2], [3, 4]])
print(a.flatten())  # → [1 2 3 4]


[1 2 3 4]


In [43]:
  # Stack Arrays
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(np.vstack((a, b)))
print(np.hstack((a, b)))


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [44]:
# np.random.choice() – Randomly pick from a list
arr = np.array([10, 20, 30, 40])
print(np.random.choice(arr, 3))


[30 10 40]


In [45]:
# np.random.shuffle() – Shuffle array in-place
arr = np.array([1, 2, 3, 4])
np.random.shuffle(arr)
print(arr)


[3 4 2 1]


In [46]:
np.random.seed(42)
print(np.random.randint(1, 10, 5))


[7 4 8 5 7]


In [ ]:
 # np.random.seed()
np.random.seed(42)
print(np.random.randint(1, 10, 5))


[7 4 8 5 7]


In [54]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [55]:
print(a.shape)

(4,)


In [51]:
a=np.array([[1],[2],[3]])
print(a)

[[1]
 [2]
 [3]]


In [52]:
print(a.shape)

(3, 1)
